# Generated by Django 4.2.4 on 2023-08-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_alter_main_slider_urlto'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='subdirectories',
            field=models.ManyToManyField(blank=True, to='store.subdirectory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='about_product',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='additional_images',
            field=models.ManyToManyField(blank=True, related_name='last_slider+', to='images.image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='character',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='main_slider+', to='images.image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subdirectories',
            field=models.ManyToManyField(blank=True, to='store.subdirectory'),
        ),
        migrations.AlterField(
            model_name='service',
            name='mini_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_description',
            field=models.TextField(blank=True),
        ),
    ]
