# Generated by Django 4.2.4 on 2023-08-24 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_catalog_subdirectories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Main_slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('urlTo', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='catalog',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_render',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='additional_images',
            field=models.ManyToManyField(blank=True, related_name='last_slider+', to='store.image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='main_slider+', to='store.image'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.image'),
        ),
    ]
