# Generated by Django 4.2.4 on 2023-08-24 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_image_delete_main_slider'),
        ('store', '0003_image_main_slider_catalog_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='additional_images',
            field=models.ManyToManyField(blank=True, related_name='last_slider+', to='images.image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='main_slider+', to='images.image'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.image'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
