# Generated by Django 4.2.4 on 2023-08-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_catalog_available_product_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_render',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
