# Generated by Django 4.2.4 on 2023-08-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_catalog_image_alter_product_additional_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_slider',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subdirectory',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
