# Generated by Django 4.2.4 on 2023-08-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_main_slider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='~/images/images/'),
        ),
        migrations.AlterField(
            model_name='main_slider',
            name='image',
            field=models.ImageField(upload_to='~/images/images/'),
        ),
    ]
