# Generated by Django 4.2.4 on 2023-08-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_alter_image_image_alter_main_slider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_slider',
            name='urlTo',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
