# Generated by Django 4.2.4 on 2023-08-24 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_image_main_slider_catalog_available_and_more'),
        ('images', '0006_remove_image_name_remove_main_slider_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
