# Generated by Django 4.2.4 on 2023-08-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('sended_to_mail', models.CharField(max_length=40)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('sended_to_mail', models.CharField(max_length=40)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('product', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('sended_to_mail', models.CharField(max_length=40)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('sended_to_mail', models.CharField(max_length=40)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('service_name', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
